import pyautogui
import time

pyautogui.FailSafeException

time.sleep(5)

for i in range(999):
    pyautogui.write("MAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA IMMMMMMMMMMMMMMMMMMMMMM INNNNNNNNNNNNNNNNN LOOOOOOOOOOOOVVVVVVVVVVVVVVVVEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE WIIIIIIIIIIIIIIIIITHHHHHHHHHHHHHHHHHHHHHHHHHHHHH AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA CRRRRRRRIIIIIIIIIIIIIIIMMMMMMMMMMMMIIIIIIIIIIIINNNNNNNNNNAAAAAAAAAAAAALLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL")
    #  pyautogui.hotkey('Win', '.')
    #  pyautogui.press("enter")
    #  pyautogui.hotkey('esc')
    time.sleep(5)
    # pyautogui.write("jinne mannu maar sutya ...oho")
    pyautogui.press("enter")
    time.sleep(5)
